env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: [

]
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "tsconfig.json"
ignorePatterns:
  - "lampsz/**/*.js"
  - "client/__mocks__/*.js"
  - "client/tests/*.tsx"
plugins:
  - react
rules:
  react/no-unescaped-entities: off


