tools:
  exceptions: https://sentry.io/organizations/dcsil/projects/454-pmbl/?project=6742330
  logging: https://service.us2.sumologic.com/ui/?appName=dcsil-team-app
  ci: https://github.com/dcsil/Lampsz-App/actions

services:
  production:

docs:
  getting_started: https://github.com/dcsil/Lampsz-App

commands:
  bootstrap: script/bootstrap
