tools:
  exceptions: https://sentry.io/organizations/dcsil/projects/lampsz/?project=6742330
  logging: https://service.us2.sumologic.com/ui/?appName=dcsil-team-app
  ci: https://github.com/dcsil/Lampsz-App/actions

services:
  production: https://github.com/dcsil/Lampsz-App

docs:
  getting_started: https://github.com/dcsil/Lampsz-App

commands:
  bootstrap: script/bootstrap
  database:
    migrate: python manage.py migrate
  server: webpack --mode production && python manage.py runserver
  test: python manage.py test && npm test
