#!/usr/bin/env bash

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. >/dev/null 2>&1 && pwd )"

if [ ! -f "$PROJECT_DIR/.env" ]; then
  echo "==== ENV ==========================================================================================================="
  cp "$PROJECT_DIR/.env.example" "$PROJECT_DIR/.env"
fi

# Docker Compose
echo ""
echo "==== Docker Compose ============================================================================================="
docker-compose up -d
