#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. >/dev/null 2>&1 && pwd )"

echo "==== System Dependencies ========================================================================================"
$SCRIPT_DIR/dependencies


echo "==== Project Dependencies ======================================================================================="
cd "$PROJECT_DIR" && poetry install
cd "$PROJECT_DIR" && npm install
