#!/usr/bin/env bash

install_poetry() {
  echo "Installing Poetry"
  curl -sSL https://install.python-poetry.org | python3 -
}


install_node() {
  echo "Installing Node"
  sudo apt-get update
  sudo apt-get install nodejs
}


# Check for installations
command -v node > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "node already installed"
else
  install_node
fi

command -v poetry > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "Poetry already installed"
else
  install_poetry
fi
