from django.contrib import messages
from django.contrib.auth import authenticate, logout
from django.contrib.messages import get_messages
from django.http import JsonResponse
from django.middleware.csrf import get_token
from rest_framework import status
from rest_framework.authentication import BasicAuthentication, SessionAuthentication
from rest_framework.decorators import (
    api_view,
    authentication_classes,
    permission_classes,
)
from rest_framework.permissions import IsAuthenticated

from lampsz.apis import models, serializers
from lampsz.apis.services import login_user
from lampsz.apis.utils import UserType, has_unique_error

__all__ = [
    "CSRF_HEADER",
    "bad_credentials",
    "csrf_set",
    "login_success",
    "logout_success",
    "failed_consent",
    "login_view",
    "register_view",
    "logout_view",
    "get_session_view",
    "get_csrf_view",
    "get_auth_messages_view",
]

# Constants
CSRF_HEADER = "X-CSRFToken"

# Response messages
bad_credentials = "Incorrect username or password!"
csrf_set = "CSRF cookie set"
login_success = "Login successful!"
logout_success = "Logout successful!"
register_success = "Successfully register and login!"
failed_consent = "Failed to login due to denied consent."


@api_view(["POST"])
def login_view(request):
    """
    Login user and returns user ID, username, and user type if credentials are
    valid, otherwise respond with 404 Not Found.
    """
    username = request.data.get("username")
    password = request.data.get("password")
    user = authenticate(request, username=username, password=password)
    if user is None:
        return JsonResponse(
            {"message": bad_credentials}, status=status.HTTP_404_NOT_FOUND
        )

    login_user(request, user)
    messages.success(request, login_success)
    return JsonResponse(
        {
            "userId": request.user.id,
            "username": request.user.username,
            "userType": request.session.get("user_type", UserType.NONE),
        }
    )


@api_view(["GET"])
def logout_view(request):
    """
    Wrapper around Django's built-in logout view that returns a JsonResponse.
    """
    logout(request)
    messages.success(request, logout_success)
    return JsonResponse({}, status=status.HTTP_200_OK)


@api_view(["POST"])
def register_view(request):
    """
    Creates a new User and Company object and returns user ID, username, and
    user type if register data is valid, otherwise return the validation errors.
    """
    user_serializer = serializers.UserSerializer(data=request.data)
    if user_serializer.is_valid():
        user = user_serializer.save()
        models.Company.objects.create(user=user)
        login_user(request, user)
        messages.success(request, register_success)
        return JsonResponse(
            {
                "userId": request.user.id,
                "username": request.user.username,
                "userType": request.session.get("user_type", UserType.NONE),
            },
            status=status.HTTP_201_CREATED,
        )

    errors = user_serializer.errors
    if has_unique_error("username", errors) or has_unique_error("email", errors):
        return JsonResponse(errors, status=status.HTTP_409_CONFLICT)
    else:
        return JsonResponse(errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(["GET"])
@authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([IsAuthenticated])
def get_session_view(request):
    """
    Returns user ID, username, and user type of the user that is logged in.
    """
    return JsonResponse(
        {
            "userId": request.user.id,
            "username": request.user.username,
            "userType": request.session.get("user_type", UserType.NONE),
        }
    )


@api_view(["GET"])
def get_csrf_view(request):
    """
    Returns CSRF token generated by Django.
    """
    response = JsonResponse({"message": csrf_set})
    response[CSRF_HEADER] = get_token(request)
    return response


@api_view(["GET"])
def get_auth_messages_view(request):
    """
    Returns all the messages generated during authentication.
    """
    serialized = [
        {"message": message.message, "level": message.level_tag}
        for message in get_messages(request)
    ]
    return JsonResponse({"messages": serialized})
