# Generated by Django 4.1.3 on 2022-11-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencer",
            name="age",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="influencer",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencer",
            name="subscribers",
            field=models.IntegerField(default=0),
        ),
    ]
