# Generated by Django 4.1.3 on 2022-11-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_influencer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
