# Generated by Django 4.1.3 on 2022-11-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_category_location_remove_influencer_tiktokuserid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="founded",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apis.location",
            ),
        ),
    ]
