# Generated by Django 4.1.3 on 2022-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_user_is_influencer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='about',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='tiktokUsername',
        ),
        migrations.AddField(
            model_name='influencer',
            name='home_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='platform',
            field=models.CharField(choices=[('YT', 'Youtube')], default='YT', max_length=10),
        ),
        migrations.AddField(
            model_name='influencer',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
