# Generated by Django 4.1.3 on 2022-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_influencer_shortbio"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="shortBio",
            field=models.TextField(default=""),
        ),
    ]
