# Generated by Django 4.1.3 on 2022-11-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_rename_about_influencer_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="about",
            new_name="description",
        ),
        migrations.AddField(
            model_name="company",
            name="shortBio",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="influencer",
            name="age",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="influencer",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencer",
            name="shortBio",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="influencer",
            name="subscribers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencer",
            name="tiktokUsername",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
