# Generated by Django 4.1.3 on 2022-11-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_alter_company_about_alter_company_founded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="founded",
            field=models.DateField(blank=True, null=True),
        ),
    ]
