# Generated by Django 4.1.3 on 2022-12-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_rename_about_company_description_company_shortbio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="influencer",
            name="tiktokUsername",
        ),
    ]
