# Generated by Django 4.1.3 on 2022-11-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_alter_company_about_alter_company_founded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apis.location",
            ),
        ),
    ]
