# Generated by Django 4.1.3 on 2022-12-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_remove_influencer_tiktokusername"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingtask",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
