# Generated by Django 4.1.3 on 2022-12-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0007_remove_company_founded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
