# Generated by Django 4.1.3 on 2022-12-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_company_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingtask',
            old_name='price',
            new_name='compensation',
        ),
        migrations.RenameField(
            model_name='marketingtask',
            old_name='postedDate',
            new_name='posted_date',
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='deliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtask',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
