# Generated by Django 4.1.3 on 2022-12-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_rename_price_marketingtask_compensation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='shortBio',
        ),
        migrations.AddField(
            model_name='company',
            name='short_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
