# Generated by Django 4.1.3 on 2022-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0009_rename_price_marketingtask_compensation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingtask",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
