# Generated by Django 4.1.3 on 2022-12-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_company_shortbio_company_short_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='shortBio',
            new_name='short_bio',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='channel_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
