# Generated by Django 4.1.3 on 2022-12-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_marketingtask_image'),
        ('apis', '0011_rename_shortbio_influencer_short_bio_and_more'),
    ]

    operations = [
    ]
