# Generated by Django 4.1.3 on 2022-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_delete_location_remove_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingtask',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
