# Generated by Django 4.1.3 on 2022-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0014_alter_marketingtask_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencer",
            name="channel_id",
            field=models.CharField(default="", max_length=400),
            preserve_default=False,
        ),
    ]
