# Generated by Django 4.1.3 on 2022-12-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_marketingtask_active'),
        ('apis', '0016_remove_influencer_likes_and_more'),
    ]

    operations = [
    ]
