# Generated by Django 4.1.3 on 2022-12-04 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_merge_20221204_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(default=datetime.date.today)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.influencer')),
                ('marketing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.marketingtask')),
            ],
        ),
    ]
