# Generated by Django 4.1.3 on 2022-12-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_taskapplication'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskapplication',
            constraint=models.UniqueConstraint(fields=('influencer', 'marketing_task'), name='unique_influencer_marketing_task'),
        ),
    ]
