# Generated by Django 4.1.3 on 2022-12-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_taskapplication_unique_influencer_marketing_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskapplication',
            options={'ordering': ('similarity',)},
        ),
        migrations.AddField(
            model_name='taskapplication',
            name='similarity',
            field=models.FloatField(default=0.0),
        ),
    ]
